### ISSUE TITLE
Access error for config file /home/keepassxc/.config/keepassxc/keepassxc.ini

### ISSUE THREAD

**Issue by tylert** [westonsteimel/container-library-keepassxc#1]
(Awesome Dockerfile, btw.)

When ${HOME}/.config/keepassxc is empty, the error "Access error for config file /home/keepassxc/.config/keepassxc/keepassxc.ini" appears when viewing the Settings screen.

It would appear that none of the settings in Keepassxc are being preserved just as if the volume was read-only.

The run command that was used is the same as the one suggested in the Dockerfile, namely:
```
 docker run -d \
		-v /tmp/.X11-unix:/tmp/.X11-unix \
		-v /etc/machine-id:/etc/machine-id:ro \
		-v /usr/share/X11/xkb:/usr/share/X11/xkb/:ro \
		-v ${HOME}/.config/keepassxc:/home/keepassxc/.config/keepassxc \
		-e DISPLAY=unix${DISPLAY} \
		westonsteimel/keepassxc
```
(I merely added a "-v ${HOME}/.keepassxc:/srv" to gain access to my existing .kdbx data files.)

This was tested on Debian 10.0.1 Buster amd64 with the "official" Docker package...
```
~$ docker --version
Docker version 18.09.1, build 4c52b90
```

**Comment by westonsteimel** [comment]
Yes, you'll have to create the directory `${HOME}/.config/keepassxc` as your local user first, otherwise it seems that docker creates it with root user as the owner, and then the non-root user within the docker container is unable to write to it.

**Comment by tylert** [comment]
Excellent, forgot to check that, thanks.  Would you mind if I added that to the README?

**Comment by westonsteimel** [comment]
Feel free to update it.  Thanks!
